### ISSUE TITLE
Exception: a must be non-empty

### ISSUE THREAD

**Issue by sholsapp** [yhenon/keras-frcnn#42]
This error pops up periodically while training, and what action to take isn't very clear. Is this a failure, a warning, informational, something else?

**Comment by yhenon** [comment]
I've had a look at the issue here - it seems to be due to calling `np.random.choice` on an empty list. Full explanation:
- the RPN gets a list of N bounding boxes
- the bounding boxes are either positive samples (IOU>0.5 to a ground truth box), negative samples (0.1<IOU<0.5), or discarded (IOU<0.5)
- a random subset of bounding boxes are retained for training (using `np.random.choice` to chose them).
- however if there are not enough negative candidates, this exception gets throws, and the code moves to the next sample.

I'll go ahead and add an explicit check to fix this.

**Comment by connorlee77** [comment]
Has this been fixed?

**Comment by shahruk10** [comment]
Hi yhenon, 

Essentially this can be fixed by checking if the length of pos_samples and neg_samples are greater than zero right? I added a else block that assigns the previous non-zero pos & neg samples to the current iteration's selected pos & neg samples.

However I was wondering if this batch may bias the classifier which might bias the RPN. Is it better to just move on to the next sample without  training the classifier ?

**Comment by wkelongws** [comment]
I am also having the same exception when running on my own dataset.

**Comment by syeddanish41** [comment]
@yhenon If I can understand correctly that the slices generated that you called the "samples" if they do not have a bounding box in that region it throws an Exception. Thus if my image has a lot of background with smaller boxes I will get lot of Exceptions but still the model is training. right?

**Comment by HuangBo-Terraloupe** [comment]
Is this problem already solved?
It also does not work on my dataset:

{'Rooftop_Area': 80822, 'Roof_Window': 60841, 'Solar_Thermal_Panel': 9077, 'Chimney/Ventilation_Pipe': 51913, 'bg': 0}

In my dataset there are also some thing very small, the bounding box will be very tiny.
So the training will fail?

**Comment by HuangBo-Terraloupe** [comment]
I fix the problem by map the 'background' to the last class not 0. 
class_mapping['bg'] = len(class_mapping)

**Comment by shuuchen** [comment]
@HuangBo-Terraloupe 
Hi, I fixed the code as you but still got the exception.
So why the training will fail if the bounding box is too small?

**Comment by shuuchen** [comment]
By the way, I found that exception happens when neg_samples in the train_frcnn.py is [].
But it does not happen when pos_samples is [].

Is neg_samples a must?

**Comment by DanMossa** [comment]
I'm also experiencing this problem. So the best course of action would be to make `self.anchor_box_scales` bigger?

**Comment by rajark** [comment]
receiving error on "Exception: a must be non-empty" with old code and also new code.   2 months before I have trained with few data's(with old code) and training is completed without error,  I have not changed any old code, receiving error in both new & old data set(previously used)... I have tried for fresh training and also incremental training in both old & new version of code, still getting error...
can you please advice on that...?

**Comment by Nico3ole** [comment]
@HuangBo-Terraloupe @shuuchen @DanMossa @rajark
Did you guys fix this problem? I am also getting this error, when training with small bounding boxes. How small are yours? Mine ranges from 5x5 to 45x45.

**Comment by chaodewen** [comment]
@rajark same with you

**Comment by ps793** [comment]
I figure out this problem for small object using keras faster-rcnn. You may need to change 
R = roi_helpers.rpn_to_roi(P_rpn[0], P_rpn[1], C, K.image_dim_ordering(), use_regr=True, overlap_thresh=0.9, max_boxes=300); overlap_thresh need to change to large number from 0.7 to 0.9 or bigger. because small object may have some problem on overlapping and nms
